// import "./globals.scss";
//
// export const metadata = {
//   title: "Scam Devs",
//   description: "Generated by create next app",
//     icons: {
//       icon: '/sd.png',
//     },
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang='en'>
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.js
import "./globals.scss";
import TranslationsProvider from './i18n-provider';
// import { useState, useEffect } from 'react'; // Можно добавить позже для синхронизации lang атрибута

export const metadata = {
    title: "Scam Devs",
    description: "Scam devs team",
    icons: {
        icon: '/sd.png',
    },
};
const i18nNamespaces = ['translation']; // Глобально нужные пространства имен

// Убираем params: { locale }
export default function RootLayout({ children }) {
    const initialLocale = 'en';

    return (
        <html lang={initialLocale}>
        <body>
        <TranslationsProvider
            locale={undefined}
            namespaces={i18nNamespaces}
        >
            {children}
        </TranslationsProvider>
        </body>
        </html>
    );
}