import "./globals.scss";

export const metadata = {
  title: "Scam Devs",
  description: "Generated by create next app",
    icons: {
      icon: '/sd.png',
    },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
